version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard_db
      MYSQL_USER: vincenzofdg
      MYSQL_PASSWORD: vincenzofdg
    ports:
      - 3001:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: db_admin
    restart: always
    ports:
      - 3002:8080
    depends_on:
      - mysql
