name: Backend Branch on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: backend_vps
          folder: database/